apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parser-py-configmap
data:
  parser.ini: |-
    [default]
    {{- if .Values.debug }}
    debug = {{ .Values.debug }}
    {{- end }}

    [database]
    # url = postgresql+psycopg2://{{ include "binder-launches.dbURL" . | quote }}
    url = postgresql+psycopg2://{{ template "binder-launches.dbURL" . }}
    {{- if .Values.db.upgrade }}
    upgrade = {{ .Values.db.upgrade }}
    {{- end }}
    {{- if .Values.db.chunkTimeInterval }}
    chunk_time_interval = {{ .Values.db.chunkTimeInterval }}
    {{- end }}
    {{- if .Values.db.dataRetentionInterval }}
    data_retention_interval = {{ .Values.db.dataRetentionInterval }}
    {{- end }}

    [parser]
    {{- if .Values.parser.until }}
    until = {{ .Values.parser.until }}
    {{- end }}
    {{- if .Values.parser.deleteOld }}
    delete_old = {{ .Values.parser.deleteOld }}
    {{- end }}
    {{- if .Values.parser.continuous }}
    continuous = {{ .Values.parser.continuous }}
    {{- end }}
