apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-parser-py
  labels:
    app: parser-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser-py
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: parser-py
      annotations:
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ include (print $.Template.BasePath "/parser-py/configmap.yaml") . | sha256sum }}
    spec:
      nodeSelector: {{ toJson .Values.parser.nodeSelector  }}
      containers:
        - name: parser-py
          image: "{{ .Values.parser.image.repository }}:{{ .Values.parser.image.tag }}"
          imagePullPolicy: {{ .Values.parser.image.pullPolicy }}
          resources:
            {{- .Values.parser.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: parser-py-config
              mountPath: "/parser_py/parser.ini"
              subPath: "parser.ini"
              readOnly: true
      volumes:
        - name: parser-py-config
          configMap:
            name: {{ .Release.Name }}-parser-py-configmap
