apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  # `|-` is for declaring a multi-line string
  config.js: |-
    const config = {
    {{- if .Values.port }}
    port: {{ .Values.port }},
    {{- end }}
    {{- if .Values.debug }}
    debug: {{ .Values.debug }},
    {{- end }}
    //db: "postgres://{{ template "binder-launches.dbURL" . }}"
    db: {{ printf "postgres://%s" (include "binder-launches.dbURL" .) | quote }}
    };
    module.exports = config;
