apiVersion: v1
kind: Service
metadata:
  name: {{ include "binder-launches.fullname" . }}
  labels:
    {{- include "binder-launches.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3001
    protocol: TCP
    name: http
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "binder-launches.selectorLabels" . | nindent 4 }}
