name: "docker build & push"

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: GitHub Environment Variables Action
        # to get CI_SHA_SHORT env variable
        uses: FranzDiebold/github-env-vars-action@v2.1.0
      - name: Build and push parser_py
        id: docker_build_parser_py
        uses: docker/build-push-action@v2
        with:
          file: ./helm_chart/images/parser_py/Dockerfile
          push: true
          tags: bitnik/binder-launches-parser-py:${{ env.CI_SHA_SHORT }}
      - name: Image digest
        run: echo ${{ steps.docker_build_parser_py.outputs.digest }}
      - name: Build and push react app
        id: docker_build_react
        uses: docker/build-push-action@v2
        with:
          file: ./helm_chart/images/binder_launches/Dockerfile
          push: true
          tags: bitnik/binder-launches:${{ env.CI_SHA_SHORT }}
      - name: Image digest
        run: echo ${{ steps.docker_build_react.outputs.digest }}
